apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-ai-agents
  labels:
    app: smart-ai-agents
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-ai-agents
  template:
    metadata:
      labels:
        app: smart-ai-agents
    spec:
      containers:
      - name: smart-ai-agents
        image: <your-docker-image>
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
